export const FETCH_PRODUCTS =  "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_BY_SIZE =  "FETCH_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE =  "ORDER_PRODUCTS_BY_PRICE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "EMOVE_FROM_CART";
